version: "3.8"
services:
  mongo:
    container_name: AnansiDb
    image: mongo:latest
    volumes:
      - ${MONGO_DATA}:/data/db
      - ${MONGO_DUMP}:/dump
    ports:
      - 27021:27017

  redis:
    container_name: AnansiRedis
    image: redis:latest
    ports:
      - 6378:6379
    volumes:
      - ${REDIS_DATA}:/data
